name: "Podcast Generator"
author: "Camille Dunning"
description: "Generates a feed for podcast from a YAML file."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: "Committer's email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "Committer's name"
    required: true
    default: ${{ github.actor }}
